<a href="https://colab.research.google.com/github/moizmaj1k/MachineLearning/blob/main/ML_05_SavingTrainedModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline
import warnings
from sklearn.exceptions import ConvergenceWarning
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [2]:
df = pd.read_csv('ML_02_house_price.csv')
df.head()

area  rooms   price
0  2104      3  399900
1  1600      3  329900
2  2400      3  369000
3  1416      2  232000
4  3000      4  539900

In [3]:
df = df.drop('rooms', axis=1)
df

area   price
0   2104  399900
1   1600  329900
2   2400  369000
3   1416  232000
4   3000  539900
5   1985  299900
6   1534  314900
7   1427  198999
8   1380  212000
9   1494  242500
10  1940  239999
11  2000  347000
12  1890  329999
13  4478  699900
14  1268  259900
15  2300  449900
16  1320  299900
17  1236  199900
18  2609  499998
19  3031  599000
20  1767  252900
21  1888  255000
22  1604  242900
23  1962  259900
24  3890  573900
25  1100  249900
26  1458  464500
27  2526  469000
28  2200  475000
29  2637  299900
30  1839  349900
31  1000  169900
32  2040  314900
33  3137  579900
34  1811  285900
35  1437  249900
36  1239  229900
37  2132  345000
38  4215  549000
39  2162  287000
40  1664  368500
41  2238  329900
42  2567  314000
43  1200  299000
44   852  179900
45  1852  299900
46  1203  239500

In [4]:
# Fitting a linear regression model
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(df[['area']], df[['price']])

LinearRegression()

In [9]:
lr.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[743896.93104994]])

<h3>We did this in ML_02 lecture. This is a trained linear regression model and we will now learn how to save it for using the same trained model later on without needing to train it again.</h3>

<h3>Approach 1(pickle library)</h3>

In [10]:
import pickle
# pickle is a library for dumping and loading files

In [11]:
with open('model_pickle', 'wb') as f:
  pickle.dump(lr, f)

# This will create a file named 'model_pickle'
# wb(write binary) we will write binary data to this file
# pickle.dump will take our model and save it in the file

In [12]:
with open('model_pickle', 'rb') as f:
  model = pickle.load(f)

# This opens the file we saved in read binary mode
# we can load the model in a variable and this way we have our pretrained model

In [14]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[743896.93104994]])

<h3>Approach 2(sklearn joblib)</h3>

In [16]:
!pip install joblib

In [18]:
import joblib

In [19]:
joblib.dump(lr, 'model_joblib')

['model_joblib']

In [20]:
model2 = joblib.load('model_joblib')

In [21]:
model2.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[743896.93104994]])